<a href="https://colab.research.google.com/github/MyDearGreatTeacher/AI_and_security/blob/master/numpy%E7%AC%AC%E4%B8%80%E5%A0%82%E8%AA%B2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [0]:
import numpy as np
np.random.seed(0) 

x1 = np.random.randint(10, size=6) 
x2 = np.random.randint(10, size=(3, 4)) 
x3 = np.random.randint(10, size=(3, 4, 5))  


In [7]:
x1

array([5, 0, 3, 3, 7, 9])

In [8]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])